project:
  type: book

book:
  title: "gusty"
  author: "Chris Cardillo"
  date: "4/17/2023"
  chapters:
    - index.qmd
    - gusty-basics.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



