project:
  type: book

book:
  title: ""
  favicon: media/logo/favicon.png
  navbar:
    pinned: TRUE
    left: 
      - icon: github
        href: https://github.com/chriscardillo/gusty
  sidebar: 
    logo: media/logo/logo_500.svg
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - gusty-basics.qmd
        - task-dependencies.qmd
        - task-groups.qmd
        - many-dags.qmd
    - part: "Doing More"
      chapters:
        - using-constructors.qmd
        - multi-tasking.qmd
        - custom-operators.qmd
  appendices: 
    - create-dag-args.qmd
format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt
