project:
  type: book

book:
  title: ""
  # author: "Chris Cardillo"
  # date: "4/17/2023"
  sidebar: 
    logo: media/logo/logo_500.svg
    tools:
    - icon: github
      href: https://github.com/chriscardillo/gusty
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - gusty-basics.qmd
        - task-dependencies.qmd
format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt
