project:
  type: book

book:
  title: "gusty"
  author: "Chris Cardillo"
  date: "4/17/2023"
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - gusty-basics.qmd
        - task-dependencies.qmd
format:
  html:
    theme: materia
  pdf:
    documentclass: scrreprt
